name: Node CD

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: dist
  
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        # list of Docker images to use as base name for tags
        images: |
          docker.pkg.github.com/husgutt/prosjektore/prosjektore-web-api
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{raw}}
    - name: Download built artifact
      uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public
    - name: Login to github
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
      
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
